"""Auto-generated from the original Persian Doz Cloudflare Worker (texts.js).

Every user-facing string and message-formatting function from the JS bundle,
converted 1:1 into Python. Plain strings stay as strings; JS arrow-function
templates become Python functions returning f-strings with identical output.
"""
from __future__ import annotations
from typing import Any, Callable, Union

TextValue = Union[str, Callable[..., str], dict]

T: dict[str, dict[str, TextValue]] = {
    "fa": {
        "welcome": "به ربات پرشین دوز خوش اومدی.\n\nاینجا میتونی دوز 7 ستونه بازی کنی، سکه جمع کنی و رتبه بگیری.\nبرای شروع یکی از گزینه های پایین رو بزن.",
        "mainMenuTitle": "پرشین دوز 🎮\n\nمنوی اصلی 📋\nیک گزینه را انتخاب کنید:",
        "btnLeague": "لیگ 🏅",
        "btnPlayFriends": "بازی با دوستان 👫",
        "btnRandomMatch": "رقابت ناشناس ⛳",
        "btnScoreRank": "امتیاز و رتبه 🏅",
        "btnHistory": "تاریخچه بازی 📜",
        "btnMarket": "بازار 💰",
        "btnAccount": "حساب 💳",
        "btnCoinsProfile": "سکه و پروفایل 💰",
        "btnSupport": "پشتیبانی 📞",
        "btnOtherBots": "رباتهای دیگر 👀",
        "btnTutorial": "آموزش بازی 💡",
        "btnMenu": "منو 📋",
        "btnNewGame": "بازی جدید 🔁",
        "btnResign": "تسلیم 🚫",
        "btnLanguage": "زبان 🌐",
        "btnBack": "بازگشت ⬅️",
        "btnClose": "بستن ✖️",
        "btnPlayWith": "بازی با",
        "playFriendsIntro": "بازی با دوستان 👫\n\nروی دکمه پایین بزن، بعد از لیست تلگرام یک پیوی یا گروه انتخاب کن.\nدعوت بازی همونجا ارسال میشه و دوستت با زدن قبول بازی وارد بازی میشه.\n\nاین بخش امتیاز، سکه و رتبه را تغییر نمیده و فقط برای سرگرمی و تمرین کردن با بقیه هست.",
        "btnChooseFriendOrGroup": "انتخاب دوست یا گروه 🎮",
        "btnAddFriend": "افزودن دوست ➕",
        "btnAddFriendById": "افزودن با آیدی 🔢",
        "btnFriendList": "لیست دوستان 👥",
        "btnFriendRequests": "درخواست‌ها 📨",
        "btnGameHistory": "تاریخچه بازی 📜",
        "friendListTitle": "لیست دوستان 👥\nبرای شروع بازی، روی نام دوستت بزن:",
        "friendRequestsTitle": "درخواست‌های دوستی 📨\nقبول یا رد کن:",
        "askFriendId": "آیدی عددی کاربر مورد نظر را ارسال کن:",
        "friendRequestSent": lambda name: f"""درخواست دوستی برای {name} ارسال شد. ✅""",
        "friendRequestReceivedButtons": lambda name: f"""{name} می‌خواد باهات دوست بشه. 👋""",
        "friendAccepted": lambda name: f"""شما و {name} اکنون دوست هستید! 🎉""",
        "friendAcceptedToast": "دوست اضافه شد ✅",
        "friendRejectedNotice": lambda name: f"""{name} درخواست دوستی شما را رد کرد.""",
        "noSuchUser": "کاربری با این آیدی پیدا نشد. آیدی رو بررسی کن و دوباره بفرست.",
        "cannotAddSelf": "نمی‌تونی خودت رو دوست خودت کنی! 😄",
        "alreadyFriends": "شما قبلا با این کاربر دوست هستید.",
        "friendBusy": "این دوست الان در حال بازی دیگه‌ای است.",
        "friendRemoved": lambda name: f"""{name} از لیست دوستان شما حذف شد.""",
        "btnAcceptInvite": "قبول ✅",
        "btnRejectInvite": "رد ❌",
        "gameInviteSent": lambda name: f"""درخواست بازی برای {name} ارسال شد. منتظر پاسخ بمون. ⏳""",
        "gameInviteReceived": lambda name: f"""{name} می‌خواد باهات بازی کنه. 🎮""",
        "gameInviteAccepted": "درخواست بازی قبول شد! 🎉",
        "gameInviteRejectedByYou": "درخواست بازی رد شد.",
        "gameInviteRejectedNotice": lambda name: f"""{name} درخواست بازی شما را رد کرد. 😔""",
        "gameInviteExpired": "این درخواست بازی دیگه معتبر نیست.",
        "noFriendsYet": "فعلا دوستی نداری.\nبعد از بازی با یک نفر، از دکمه «افزودن دوست» به دوستانت درخواست بفرست.",
        "noRequestsYet": "درخواست فعالی نداری.",
        "sendInviteLinkPrompt": "این لینک رو برای کسی که میخوای باهاش دوست بشی بفرست.\nبا باز کردن این لینک، یک درخواست دوستی برای تو ارسال میشه که باید قبولش کنی.\n\nلینک درخواست دوستی شما:",
        "friendAdded": lambda name: f"""{name} با موفقیت به لیست دوستان شما اضافه شد. 🎉""",
        "friendRequestReceived": lambda name: f"""{name} میخواد باهات دوست بشه.\nبرای شروع بازی دوستانه، دوباره وارد بخش «بازی با دوستان» شو و از لیست دوستان انتخابش کن.""",
        "friendRequestAlreadySent": lambda name: f"""قبلا برای {name} درخواست دوستی فرستادی. منتظر پاسخ بمون.""",
        "cannotAddExistingFriend": "شما قبلا با این کاربر دوست هستید.",
        "randomMatchIntro": "رقابت ناشناس ⛳\n\nاینجا میتونی به صورت ناشناس با یکی از ممبرای ربات بازی کنی.\n\nبرد: +50 سکه | باخت: -50 سکه\nمساوی سکه را تغییر نمیده.\n\nهویتت به حریف نشون داده نمیشه 🕵️",
        "btnFindOpponent": "جستجوی حریف 🎯",
        "btnCancelSearch": "لغو جستجو ❌",
        "searchingOpponent": "در حال جستجوی حریف... ⏳\nهمین که یک بازیکن دیگه پیدا بشه، بازی شروع میشه.",
        "opponentFound": lambda name: f"""حریف پیدا شد! مقابل {name} بازی می‌کنی. 🎮""",
        "matchCanceled": "جستجو لغو شد. به منوی اصلی برگشتی.",
        "notSearching": "شما در حال حاضر در صف جستجو نیستید.",
        "leagueTitle": "جدول لیگ 📊",
        "leagueEmpty": "هنوز کسی امتیازی کسب نکرده.",
        "btnViewLeaderboard": "مشاهده جدول امتیازات 🏆",
        "leagueHeaders": {
            "name": "نام",
            "username": "یوزرنیم",
            "wins": "برد",
            "losses": "باخت",
            "draws": "مساوی",
            "score": "امتیاز",
        },
        "btnJoinLeague": "شرکت در لیگ 🏅",
        "joinedLeague": "شما با موفقیت در لیگ هفتگی ثبت‌نام شدید. 🎉",
        "accountTitle": "حساب کاربری 💳",
        "accountRows": {
            "field": "بخش",
            "value": "مقدار",
            "name": "نام",
            "username": "یوزرنیم",
            "usernameVisibility": "وضعیت نمایش یوزرنیم",
            "hidden": "مخفی",
            "shown": "نمایش داده می‌شود",
            "numericId": "آیدی عددی",
            "botRank": "رتبه در ربات",
            "score": "امتیاز",
            "coins": "سکه‌ها",
            "wins": "برد",
            "losses": "باخت",
            "draws": "مساوی",
        },
        "btnToggleUsername": "نمایش یوزرنیم",
        "marketTitleShort": "بازار 💰",
        "marketIntro": lambda balance: f"""بازار 💰\n\nموجودی شما: {balance} 💎\n\nاز دکمه‌های پایین استفاده کن:\n🎁 سکه روزانه: هر ۲۴ ساعت یکبار سکه رایگان بگیر.\n👥 زیرمجموعه‌گیری: با دعوت دوستات سکه جمع کن.""",
        "btnDailyCoin": "سکه روزانه 🎁",
        "btnReferral": "زیرمجموعه‌گیری 👥",
        "dailyCoinClaimed": lambda amount, balance: f"""{amount} سکه 🎉 به حساب شما اضافه شد!\nموجودی جدید: {balance} 💎""",
        "dailyCoinAlreadyClaimed": lambda hours, minutes: f"""سکه روزانه رو قبلا گرفتی. ⏳\nبرای دریافت بعدی، {hours} ساعت و {minutes} دقیقه دیگه صبر کن.""",
        "referralInfo": {
            "balance": "موجودی شما",
            "invites": "تعداد دعوتی‌ها",
            "perInvite": "پاداش هر دعوت",
            "link": "لینک دعوت اختصاصی",
        },
        "referralTitle": "زیرمجموعه‌گیری 👥",
        "supportText": lambda link: f"""برای پشتیبانی و ارتباط با ادمین، پیام بده به:\n{link}""",
        "otherBotsText": "سایر ربات‌های ما:\n\n🤖 Doz Classic Game - نسخه کلاسیک بازی دوز",
        "tutorialText": "آموزش بازی 💡\n\nدر هر نوبت یکی از ستون‌ها را انتخاب کن.\nمهره از بالای ستون میفته و پایین‌ترین خانه خالی رو پر می‌کنه.\nهرکس زودتر 4 مهره پشت سر هم افقی، عمودی یا مورب بسازه برنده می‌شه.",
        "langPrompt": "زبان مورد نظر را انتخاب کنید 🌐 / Choose your language:",
        "langSet": "زبان به فارسی تغییر یافت. 🇮🇷",
        "signupBonus": lambda amount: f"""به عنوان هدیه خوش‌آمدگویی {amount} سکه 💰 به حساب شما اضافه شد!""",
        "referralBonusReceived": lambda name, amount: f"""{name} با لینک دعوت شما وارد ربات شد. {amount} سکه 🎉 به حساب شما اضافه شد.""",
        "gameStartNotice": lambda myColor, oppColor: f"""رنگ شما: {myColor}  |  رنگ حریف: {oppColor}""",
        "boardHeader": lambda myName, myColor, oppName, oppColor: f"""شما ({myName} {myColor})\nمقابل\n{oppName} ({oppColor})""",
        "turnTimeWarning": "⚠️ فقط ۳۰ ثانیه دیگه برای حرکت وقت داری.",
        "timeoutLoss": "⏰ زمان حرکتت تموم شد. حریف برنده اعلام شد.",
        "timeoutWin": "⏰ حریف به موقع حرکت نکرد. شما برنده اعلام شدید! 🏆",
        "adminNoAccess": "شما دسترسی مدیریت ندارید.",
        "adminPanelTitle": "پنل مدیریت 🛠\nیک گزینه را انتخاب کنید:",
        "adminBtnSupport": "لینک پشتیبانی 🔗",
        "adminBtnChannel": "کانال اجباری 📢",
        "adminBtnAddAll": "افزودن سکه به همه 🎁",
        "adminBtnAddOne": "افزودن سکه به یک نفر 🎯",
        "adminBtnReferralBonus": "پاداش دعوت 🤝",
        "adminBtnSignupBonus": "پاداش عضویت اول 🆕",
        "adminBtnView": "نمایش تنظیمات ⚙️",
        "adminBtnResetUser": "ریست کاربر گیرکرده 🔄",
        "adminBtnCancel": "لغو ❌",
        "adminAskSupportLink": "لینک جدید پشتیبانی را ارسال کنید (مثال: https://t.me/YourSupport):",
        "adminAskChannel": "آیدی یا لینک کانالی که عضویت اجباری داره رو بفرست (مثال: @mychannel یا https://t.me/mychannel).\nبرای غیرفعال کردن عضویت اجباری، یک خط تیره (-) بفرست.\n\n⚠️ ربات باید عضو ادمین‌های همون کانال باشه تا بتونه عضویت کاربرها رو بررسی کنه.",
        "adminAskAddAll": "مقدار سکه‌ای که به همه کاربران اضافه شود را وارد کنید (عدد؛ می‌تواند منفی هم باشد):",
        "adminAskAddOne": "آیدی عددی کاربر و مقدار سکه را با یک فاصله وارد کنید.\nمثال: 375474045 100",
        "adminAskReferralBonus": "مقدار جدید پاداش دعوت (سکه) را وارد کنید:",
        "adminAskSignupBonus": "مقدار جدید پاداش عضویت اول (سکه) را وارد کنید:",
        "adminAskResetUser": "آیدی عددی کاربری که گیر کرده (مثلا توی یک بازی یا صف که دیگه کار نمی‌کنه) رو بفرست.\nبازی فعال اون کاربر تموم می‌شه (حریفش هم نتیجه رو می‌بینه)، از صف جستجو خارج می‌شه و هر حالت معلق دیگه‌ای هم پاک میشه.",
        "adminCanceled": "عملیات لغو شد.",
        "adminInvalidNumber": "لطفا یک عدد معتبر وارد کنید.",
        "adminInvalidFormat": "فرمت اشتباه است. مثال: 375474045 100",
        "adminUserNotFound": "کاربری با این آیدی پیدا نشد.",
        "adminSupportUpdated": lambda link: f"""لینک پشتیبانی به‌روزرسانی شد:\n{link}""",
        "adminChannelUpdated": lambda channel: f"""کانال اجباری تنظیم شد: {channel}""",
        "adminChannelDisabled": "عضویت اجباری در کانال غیرفعال شد.",
        "adminAddAllDone": lambda amount, count: f"""{amount} سکه به {count} کاربر اضافه شد. ✅""",
        "adminAddOneDone": lambda amount, name: f"""{amount} سکه به {name} اضافه شد. ✅""",
        "adminReferralBonusUpdated": lambda amount: f"""پاداش دعوت به {amount} سکه تغییر یافت. ✅""",
        "adminSignupBonusUpdated": lambda amount: f"""پاداش عضویت اول به {amount} سکه تغییر یافت. ✅\nاین مقدار فقط برای کاربران جدید اعمال می‌شود.""",
        "adminResetUserDone": lambda name: f"""{name} با موفقیت ریست شد: بازی فعال (اگه بود) پایان یافت، از صف خارج شد و حالت معلقش پاک شد. ✅""",
        "adminSettingsView": lambda s: f"""تنظیمات فعلی ⚙️\n\nلینک پشتیبانی: {s.supportLink}\nکانال اجباری: {s.requiredChannel  or  "—"}\nپاداش دعوت: {s.referralBonus} سکه\nپاداش عضویت اول: {s.signupBonus} سکه""",
        "btnJoinChannel": "عضویت در کانال 📢",
        "btnIJoined": "عضو شدم ✅",
        "channelGateMessage": "برای استفاده از امکانات ربات، ابتدا باید عضو کانال ما بشی. 📢\n\nبعد از عضویت، روی دکمه «عضو شدم ✅» بزن.",
        "channelJoinedSuccess": "عضویت شما تایید شد! ✅ حالا می‌تونی از امکانات ربات استفاده کنی.",
        "channelStillNotJoined": "هنوز عضو کانال نشدی. لطفا اول عضو شو، بعد دوباره امتحان کن. 🙏",
        "supportChannelLine": lambda link: f"""کانال ما: {link}""",
        "gameResultWin": lambda opponent: f"""نتیجه برای شما: برد 🏆\nنوع بازی: {opponent.mode}\nحریف: {opponent.name}\nبرنده: شما\nعلت پایان: {opponent.reason}\nتغییر سکه: {opponent.coinsLine}\nموجودی فعلی: {opponent.balance} 💎\n\nصفحه زیر وضعیت نهایی بازیه.""",
        "gameResultLoss": lambda opponent: f"""نتیجه برای شما: باخت 😔\nنوع بازی: {opponent.mode}\nحریف: {opponent.name}\nبرنده: حریف\nعلت پایان: {opponent.reason}\nتغییر سکه: {opponent.coinsLine}\nموجودی فعلی: {opponent.balance} 💎\n\nصفحه زیر وضعیت نهایی بازیه.""",
        "gameResultDraw": lambda opponent: f"""نتیجه برای شما: مساوی 🤝\nنوع بازی: {opponent.mode}\nحریف: {opponent.name}\nعلت پایان: {opponent.reason}\nموجودی فعلی: {opponent.balance} 💎\n\nصفحه زیر وضعیت نهایی بازیه.""",
        "modeFriend": "بازی با دوستان",
        "modeRandom": "رقابت ناشناس",
        "modeGroup": "بازی گروهی 👥",
        "btnJoinGame": "پیوستن به بازی 🎮",
        "groupWaitingMessage": lambda name: f"""{name} یک بازی جدید شروع کرد! 🎮\nبرای پیوستن به‌عنوان حریف، دکمه زیر رو بزن.""",
        "groupAlreadyActive": "همین الان یک بازی در این گروه در حال انجامه.",
        "groupCannotJoinSelf": "نمی‌تونی با خودت بازی کنی! یکی دیگه باید دکمه رو بزنه.",
        "groupSlotsFull": "این بازی قبلا دو بازیکن داره.",
        "groupNotAPlayer": "شما بازیکن این بازی نیستید.",
        "groupVsLine": lambda n1, c1, n2, c2: f"""{n1} ({c1}) 🆚 {n2} ({c2})""",
        "groupTurnLine": lambda name, color: f"""نوبت {name} {color}""",
        "reasonConnect4": "چهار در یک ردیف",
        "reasonDraw": "پر شدن تخته (مساوی)",
        "reasonResign": "تسلیم شدن",
        "reasonTimeout": "اتمام وقت حرکت",
        "reasonLeave": "ترک بازی",
        "coinsGained": lambda n: f"""+{n} 💎""",
        "coinsLost": lambda n: f"""-{n} 💎""",
        "coinsUnchanged": "بدون تغییر",
        "historyTitle": "تاریخچه بازی 📜",
        "historyEmpty": "هنوز هیچ بازی‌ای انجام ندادی.",
        "historyFields": {
            "opponent": "حریف",
            "mode": "نوع بازی",
            "result": "نتیجه",
            "reason": "علت پایان",
            "coins": "تغییر سکه",
            "duration": "مدت بازی",
            "date": "تاریخ",
        },
        "historyResultWin": "برد 🏆",
        "historyResultLoss": "باخت 😔",
        "historyResultDraw": "مساوی 🤝",
        "historyMore": "نمایش موارد بیشتر ⬇️",
        "durationSeconds": lambda s: f"""{s} ثانیه""",
        "resigned": "شما تسلیم شدید. حریف برنده اعلام شد.",
        "opponentResigned": "حریف بازی تسلیم شد. شما برنده اعلام شدید! 🏆",
        "yourTurn": "نوبت شماست",
        "waitingForOpponent": "منتظر حرکت حریف باش... ⏳",
        "invalidMove": "این ستون پر است، ستون دیگری انتخاب کن.",
        "notYourTurn": "الان نوبت شما نیست.",
        "newGameCreated": "بازی جدید شروع شد!",
        "inGameAlready": "شما در حال حاضر یک بازی فعال دارید.",
        "activeGamePrompt": "شما یک بازی نیمه‌تمام دارید. ⏳\n\nمیخوای ادامه بدی یا بازی رو ترک کنی؟\nتوجه: ترک بازی به معنی باخت است و ۵۰ سکه از شما کم و به حریف اضافه می‌شود.",
        "btnResumeGame": "ادامه بازی ▶️",
        "btnLeaveGame": "ترک بازی 🚪",
    },
    "en": {
        "welcome": "Welcome to Persian Doz Bot.\n\nHere you can play 7-column Doz (Connect Four), collect coins and climb the rank.\nTap one of the options below to start.",
        "mainMenuTitle": "Persian Doz 🎮\n\nMain Menu 📋\nChoose an option:",
        "btnLeague": "League 🏅",
        "btnPlayFriends": "Play with Friends 👫",
        "btnRandomMatch": "Random Match ⛳",
        "btnScoreRank": "Score & Rank 🏅",
        "btnHistory": "Game History 📜",
        "btnMarket": "Market 💰",
        "btnAccount": "Account 💳",
        "btnCoinsProfile": "Coins & Profile 💰",
        "btnSupport": "Support 📞",
        "btnOtherBots": "Other Bots 👀",
        "btnTutorial": "Tutorial 💡",
        "btnMenu": "Menu 📋",
        "btnNewGame": "New Game 🔁",
        "btnResign": "Resign 🚫",
        "btnLanguage": "Language 🌐",
        "btnBack": "Back ⬅️",
        "btnClose": "Close ✖️",
        "btnPlayWith": "Play with",
        "playFriendsIntro": "Play with Friends 👫\n\nTap the button below, then choose a chat or group from your Telegram list.\nAn invite will be sent there, and your friend joins the game once they accept.\n\nThis mode doesn't affect score, coins or rank — it's just for fun.",
        "btnChooseFriendOrGroup": "Choose Friend or Group 🎮",
        "btnAddFriend": "Add Friend ➕",
        "btnAddFriendById": "Add by ID 🔢",
        "btnFriendList": "Friend List 👥",
        "btnFriendRequests": "Requests 📨",
        "btnGameHistory": "Game History 📜",
        "friendListTitle": "Friend List 👥\nTap a friend's name to start a game:",
        "friendRequestsTitle": "Friend Requests 📨\nAccept or reject:",
        "askFriendId": "Send the numeric user ID of the person you want to add:",
        "friendRequestSent": lambda name: f"""Friend request sent to {name}. ✅""",
        "friendRequestReceivedButtons": lambda name: f"""{name} wants to be your friend. 👋""",
        "friendAccepted": lambda name: f"""You and {name} are now friends! 🎉""",
        "friendAcceptedToast": "Friend added ✅",
        "friendRejectedNotice": lambda name: f"""{name} declined your friend request.""",
        "noSuchUser": "No user found with that ID. Double-check it and try again.",
        "cannotAddSelf": "You can't add yourself as a friend! 😄",
        "alreadyFriends": "You're already friends with this user.",
        "friendBusy": "This friend is currently in another game.",
        "friendRemoved": lambda name: f"""{name} was removed from your friend list.""",
        "btnAcceptInvite": "Accept ✅",
        "btnRejectInvite": "Reject ❌",
        "gameInviteSent": lambda name: f"""Game invite sent to {name}. Waiting for their response. ⏳""",
        "gameInviteReceived": lambda name: f"""{name} wants to play with you. 🎮""",
        "gameInviteAccepted": "Game invite accepted! 🎉",
        "gameInviteRejectedByYou": "Game invite rejected.",
        "gameInviteRejectedNotice": lambda name: f"""{name} declined your game invite. 😔""",
        "gameInviteExpired": "This game invite is no longer valid.",
        "noFriendsYet": "You don't have any friends yet.\nAfter playing someone, use \"Add Friend\" to send them a request.",
        "noRequestsYet": "You have no pending requests.",
        "sendInviteLinkPrompt": "Send this link to whoever you want to add as a friend.\nOpening this link sends a friend request to you that you'll need to accept.\n\nYour friend request link:",
        "friendAdded": lambda name: f"""{name} was successfully added to your friend list. 🎉""",
        "friendRequestReceived": lambda name: f"""{name} wants to be your friend.\nGo back to "Play with Friends" and pick them from your friend list to start a game.""",
        "friendRequestAlreadySent": lambda name: f"""You already sent {name} a friend request. Hang tight for their answer.""",
        "cannotAddExistingFriend": "You're already friends with this user.",
        "randomMatchIntro": "Random Match ⛳\n\nPlay anonymously against another member of the bot.\n\nWin: +50 coins | Loss: -50 coins\nDraws don't change your coins.\n\nYour identity is not shown to the opponent 🕵️",
        "btnFindOpponent": "Find Opponent 🎯",
        "btnCancelSearch": "Cancel Search ❌",
        "searchingOpponent": "Searching for an opponent... ⏳\nThe game starts as soon as someone else is found.",
        "opponentFound": lambda name: f"""Opponent found! You're playing against {name}. 🎮""",
        "matchCanceled": "Search canceled. You're back at the main menu.",
        "notSearching": "You're not currently searching for a match.",
        "leagueTitle": "League Table 📊",
        "leagueEmpty": "No one has scored any points yet.",
        "btnViewLeaderboard": "View Leaderboard 🏆",
        "leagueHeaders": {
            "name": "Name",
            "username": "Username",
            "wins": "W",
            "losses": "L",
            "draws": "D",
            "score": "Score",
        },
        "btnJoinLeague": "Join League 🏅",
        "joinedLeague": "You've successfully joined the weekly league. 🎉",
        "accountTitle": "Account 💳",
        "accountRows": {
            "field": "Field",
            "value": "Value",
            "name": "Name",
            "username": "Username",
            "usernameVisibility": "Username visibility",
            "hidden": "Hidden",
            "shown": "Shown",
            "numericId": "Numeric ID",
            "botRank": "Bot rank",
            "score": "Score",
            "coins": "Coins",
            "wins": "Wins",
            "losses": "Losses",
            "draws": "Draws",
        },
        "btnToggleUsername": "Toggle username visibility",
        "marketTitleShort": "Market 💰",
        "marketIntro": lambda balance: f"""Market 💰\n\nYour balance: {balance} 💎\n\nUse the buttons below:\n🎁 Daily Coin: claim a free coin bonus once every 24 hours.\n👥 Referral: earn coins by inviting friends.""",
        "btnDailyCoin": "Daily Coin 🎁",
        "btnReferral": "Referral 👥",
        "dailyCoinClaimed": lambda amount, balance: f"""You got {amount} coins 🎉!\nNew balance: {balance} 💎""",
        "dailyCoinAlreadyClaimed": lambda hours, minutes: f"""You've already claimed your daily coin. ⏳\nCome back in {hours}h {minutes}m for the next one.""",
        "referralInfo": {
            "balance": "Your balance",
            "invites": "Invites",
            "perInvite": "Bonus per invite",
            "link": "Your invite link",
        },
        "referralTitle": "Referral 👥",
        "supportText": lambda link: f"""For support, message:\n{link}""",
        "otherBotsText": "Our other bots:\n\n🤖 Doz Classic Game - classic version of the Doz game",
        "tutorialText": "Tutorial 💡\n\nOn your turn, choose a column.\nYour piece drops from the top and fills the lowest empty cell.\nWhoever connects 4 pieces first — horizontally, vertically or diagonally — wins.",
        "langPrompt": "Choose your language 🌐 / زبان مورد نظر را انتخاب کنید:",
        "langSet": "Language set to English. 🇬🇧",
        "signupBonus": lambda amount: f"""You received {amount} coins 💰 as a welcome bonus!""",
        "referralBonusReceived": lambda name, amount: f"""{name} joined using your invite link. You received {amount} coins 🎉.""",
        "gameStartNotice": lambda myColor, oppColor: f"""Your color: {myColor}  |  Opponent's color: {oppColor}""",
        "boardHeader": lambda myName, myColor, oppName, oppColor: f"""You ({myName} {myColor})\nVS\n{oppName} ({oppColor})""",
        "turnTimeWarning": "⚠️ You have only 30 seconds remaining to make your move.",
        "timeoutLoss": "⏰ Your move timer ran out. Your opponent was declared the winner.",
        "timeoutWin": "⏰ Your opponent didn't move in time. You win! 🏆",
        "adminNoAccess": "You don't have admin access.",
        "adminPanelTitle": "Admin Panel 🛠\nChoose an option:",
        "adminBtnSupport": "Support Link 🔗",
        "adminBtnChannel": "Mandatory Channel 📢",
        "adminBtnAddAll": "Add Coins to All 🎁",
        "adminBtnAddOne": "Add Coins to One User 🎯",
        "adminBtnReferralBonus": "Referral Bonus 🤝",
        "adminBtnSignupBonus": "Signup Bonus 🆕",
        "adminBtnView": "View Settings ⚙️",
        "adminBtnResetUser": "Reset Stuck User 🔄",
        "adminBtnCancel": "Cancel ❌",
        "adminAskSupportLink": "Send the new support link (e.g. https://t.me/YourSupport):",
        "adminAskChannel": "Send the ID or link of the channel that should be mandatory to join (e.g. @mychannel or https://t.me/mychannel).\nTo disable the mandatory-join requirement, send a dash (-).\n\n⚠️ The bot must be an admin of that channel to check members' status.",
        "adminAskAddAll": "Enter the amount of coins to add to every user (a number; can be negative):",
        "adminAskAddOne": "Enter the user's numeric ID and the coin amount separated by a space.\nExample: 375474045 100",
        "adminAskReferralBonus": "Enter the new referral bonus (coins):",
        "adminAskSignupBonus": "Enter the new first-time signup bonus (coins):",
        "adminAskResetUser": "Send the numeric ID of the user who's stuck (e.g. in a game or queue that no longer responds).\nTheir active game will be ended (their opponent gets a normal result too), they'll be removed from the matchmaking queue, and any other pending state will be cleared.",
        "adminCanceled": "Operation canceled.",
        "adminInvalidNumber": "Please enter a valid number.",
        "adminInvalidFormat": "Invalid format. Example: 375474045 100",
        "adminUserNotFound": "No user found with that ID.",
        "adminSupportUpdated": lambda link: f"""Support link updated:\n{link}""",
        "adminChannelUpdated": lambda channel: f"""Mandatory channel set to: {channel}""",
        "adminChannelDisabled": "Mandatory channel join has been disabled.",
        "adminAddAllDone": lambda amount, count: f"""Added {amount} coins to {count} users. ✅""",
        "adminAddOneDone": lambda amount, name: f"""Added {amount} coins to {name}. ✅""",
        "adminResetUserDone": lambda name: f"""{name} was reset successfully: any active game was ended, they were removed from the queue, and their pending state was cleared. ✅""",
        "adminReferralBonusUpdated": lambda amount: f"""Referral bonus changed to {amount} coins. ✅""",
        "adminSignupBonusUpdated": lambda amount: f"""Signup bonus changed to {amount} coins. ✅\nThis only applies to new users going forward.""",
        "adminSettingsView": lambda s: f"""Current Settings ⚙️\n\nSupport link: {s.supportLink}\nMandatory channel: {s.requiredChannel  or  "—"}\nReferral bonus: {s.referralBonus} coins\nSignup bonus: {s.signupBonus} coins""",
        "btnJoinChannel": "Join Channel 📢",
        "btnIJoined": "I've Joined ✅",
        "channelGateMessage": "To use the bot's features, you first need to join our channel. 📢\n\nAfter joining, tap \"I've Joined ✅\".",
        "channelJoinedSuccess": "Membership confirmed! ✅ You can now use the bot's features.",
        "channelStillNotJoined": "You haven't joined the channel yet. Please join, then try again. 🙏",
        "supportChannelLine": lambda link: f"""Our channel: {link}""",
        "gameResultWin": lambda opponent: f"""Result: Win 🏆\nMode: {opponent.mode}\nOpponent: {opponent.name}\nWinner: You\nEnd reason: {opponent.reason}\nCoins: {opponent.coinsLine}\nCurrent balance: {opponent.balance} 💎\n\nFinal board below.""",
        "gameResultLoss": lambda opponent: f"""Result: Loss 😔\nMode: {opponent.mode}\nOpponent: {opponent.name}\nWinner: Opponent\nEnd reason: {opponent.reason}\nCoins: {opponent.coinsLine}\nCurrent balance: {opponent.balance} 💎\n\nFinal board below.""",
        "gameResultDraw": lambda opponent: f"""Result: Draw 🤝\nMode: {opponent.mode}\nOpponent: {opponent.name}\nEnd reason: {opponent.reason}\nCurrent balance: {opponent.balance} 💎\n\nFinal board below.""",
        "modeFriend": "Play with Friends",
        "modeRandom": "Random Match",
        "modeGroup": "Group Game 👥",
        "btnJoinGame": "Join Game 🎮",
        "groupWaitingMessage": lambda name: f"""{name} started a new game! 🎮\nTap below to join as the opponent.""",
        "groupAlreadyActive": "A game is already in progress in this group.",
        "groupCannotJoinSelf": "You can't play against yourself! Someone else needs to tap the button.",
        "groupSlotsFull": "This game already has two players.",
        "groupNotAPlayer": "You're not a player in this game.",
        "groupVsLine": lambda n1, c1, n2, c2: f"""{n1} ({c1}) 🆚 {n2} ({c2})""",
        "groupTurnLine": lambda name, color: f"""{name}'s turn {color}""",
        "reasonConnect4": "Four in a row",
        "reasonDraw": "Board full (draw)",
        "reasonResign": "Resignation",
        "reasonTimeout": "Move timeout",
        "reasonLeave": "Left the game",
        "coinsGained": lambda n: f"""+{n} 💎""",
        "coinsLost": lambda n: f"""-{n} 💎""",
        "coinsUnchanged": "No change",
        "historyTitle": "Game History 📜",
        "historyEmpty": "You haven't played any games yet.",
        "historyFields": {
            "opponent": "Opponent",
            "mode": "Mode",
            "result": "Result",
            "reason": "End reason",
            "coins": "Coins",
            "duration": "Duration",
            "date": "Date",
        },
        "historyResultWin": "Win 🏆",
        "historyResultLoss": "Loss 😔",
        "historyResultDraw": "Draw 🤝",
        "historyMore": "Show more ⬇️",
        "durationSeconds": lambda s: f"""{s}s""",
        "resigned": "You resigned. Your opponent was declared the winner.",
        "opponentResigned": "Your opponent resigned. You win! 🏆",
        "yourTurn": "Your turn",
        "waitingForOpponent": "Waiting for opponent's move... ⏳",
        "invalidMove": "That column is full, pick another one.",
        "notYourTurn": "It's not your turn yet.",
        "newGameCreated": "New game started!",
        "inGameAlready": "You already have an active game.",
        "activeGamePrompt": "You have a game in progress. ⏳\n\nDo you want to resume it or leave the game?\nNote: leaving counts as a loss — 50 coins will be deducted from you and given to your opponent.",
        "btnResumeGame": "Resume Game ▶️",
        "btnLeaveGame": "Leave Game 🚪",
    },
}


def t(lang: str, key: str, *args: Any) -> str:
    """Look up a text entry for `lang` (falling back to 'fa') and, if it is a
    formatting function, call it with `*args`. Mirrors the original t() in texts.js.
    """
    entry = T.get(lang, T["fa"]).get(key)
    if entry is None:
        entry = T["fa"].get(key)
    if callable(entry):
        return entry(*args)
    return entry
